# Generated by Django 3.1 on 2020-05-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
