# Generated by Django 3.1 on 2020-05-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risapp', '0003_auto_20200524_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
