# Generated by Django 3.1 on 2020-05-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risapp', '0004_auto_20200525_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
